project:
  type: website

website:
  title: "Pain"
  navbar:
    left:
      - href: index.qmd
      - eda.qmd
      - Model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

